spring:
  application:
    name: evaStudent
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    # 30 ???
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evaluation?useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8088
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
